#!/bin/bash
# Guardian Shield - Quick Commands Reference

echo "🛡️ Guardian Shield - Command Reference"
echo "======================================"
echo ""
echo "📌 QUICK START"
echo "=============="
echo ""
echo "1️⃣  Install & Run (First Time):"
echo "   cd backend && npm install && npm run dev"
echo "   # In another terminal:"
echo "   cd frontend && npm install && npm run dev"
echo ""
echo ""
echo "2️⃣  Run Existing Installation:"
echo "   cd backend && npm run dev"
echo "   # In another terminal:"
echo "   cd frontend && npm run dev"
echo ""
echo ""
echo "3️⃣  Using Docker Compose:"
echo "   docker-compose up"
echo ""
echo ""
echo "🌐 ACCESS POINTS"
echo "================"
echo ""
echo "Frontend:  http://localhost:5173"
echo "Backend:   http://localhost:5000"
echo "API Base:  http://localhost:5000/api"
echo ""
echo ""
echo "🧪 API TESTING"
echo "=============="
echo ""
echo "Test Vulnerability Scanner:"
echo "curl -X POST http://localhost:5000/api/scanner/vulnerabilities \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"input\":\"http://example.com?id=1 OR 1=1\"}'"
echo ""
echo ""
echo "Test Password Analysis:"
echo "curl -X POST http://localhost:5000/api/password/analyze \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"password\":\"MySecurePass123!\"}'"
echo ""
echo ""
echo "Test Chatbot:"
echo "curl -X POST http://localhost:5000/api/chat/message \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"message\":\"Tell me about SQL injection\"}'"
echo ""
echo ""
echo "Generate Password:"
echo "curl http://localhost:5000/api/password/generate?length=16"
echo ""
echo ""
echo "📁 PROJECT STRUCTURE"
echo "===================="
echo ""
echo "backend/"
echo "  ├── src/"
echo "  │   ├── routes/ (API endpoints)"
echo "  │   ├── services/ (Business logic)"
echo "  │   ├── models/ (Data models)"
echo "  │   └── server.js (Express setup)"
echo "  └── uploads/ (File storage)"
echo ""
echo "frontend/"
echo "  ├── src/"
echo "  │   ├── components/ (React components)"
echo "  │   ├── services/ (API client)"
echo "  │   ├── styles/ (CSS files)"
echo "  │   └── App.jsx (Main component)"
echo "  └── index.html"
echo ""
echo ""
echo "🔍 FEATURES"
echo "==========="
echo ""
echo "✅ Vulnerability Scanner"
echo "   - Scan URLs for SQL Injection, XSS, Path Traversal, etc."
echo "   - Risk level assessment"
echo ""
echo "✅ Virus Scanner"
echo "   - Upload files to scan for malware"
echo "   - Threat detection and reporting"
echo ""
echo "✅ Password Analyzer"
echo "   - Strength analysis (0-100)"
echo "   - Entropy calculation"
echo "   - Time-to-crack estimation"
echo "   - Secure password generation"
echo ""
echo "✅ Security Chatbot"
echo "   - Knowledge base on security topics"
echo "   - Prevention methods & best practices"
echo "   - Tool recommendations"
echo ""
echo ""
echo "📚 DOCUMENTATION"
echo "================"
echo ""
echo "README.md          - Project overview"
echo "DEVELOPMENT.md     - Development guide with examples"
echo "BUILD_SUMMARY.md   - Complete build documentation"
echo "TEST_CASES.md      - Testing scenarios & examples"
echo ""
echo ""
echo "🚀 PRODUCTION BUILD"
echo "==================="
echo ""
echo "Frontend:"
echo "  cd frontend && npm run build"
echo ""
echo "Backend:"
echo "  Already production-ready"
echo ""
echo "Docker:"
echo "  docker-compose -f docker-compose.yml up -d"
echo ""
echo ""
echo "💡 TIPS"
echo "======"
echo ""
echo "- Check browser console (F12) for frontend errors"
echo "- Check backend terminal for API logs"
echo "- Verify both servers are running before testing"
echo "- Use 'npm run dev' for development with hot reload"
echo "- Clear cache (Ctrl+Shift+Delete) if facing issues"
echo ""
echo ""
echo "❌ TROUBLESHOOTING"
echo "=================="
echo ""
echo "Port 5000 in use:"
echo "  lsof -i :5000  # Show processes"
echo "  kill -9 <PID>  # Kill process"
echo ""
echo "Port 5173 in use:"
echo "  lsof -i :5173"
echo "  kill -9 <PID>"
echo ""
echo "Module not found:"
echo "  rm -rf node_modules package-lock.json"
echo "  npm install"
echo ""
echo "CORS error:"
echo "  Ensure frontend is on localhost:5173"
echo "  Ensure backend is on localhost:5000"
echo ""
echo ""
echo "📞 SUPPORT"
echo "=========="
echo ""
echo "Check these files for detailed help:"
echo "  - DEVELOPMENT.md (Step-by-step guide)"
echo "  - TEST_CASES.md (Testing examples)"
echo "  - BUILD_SUMMARY.md (Complete reference)"
echo ""
echo ""
echo "Happy Scanning! 🛡️"
echo ""
